master_ip: 192.168.5.13
backup1_ip: 192.168.5.14
backup2_ip: 192.168.5.15

percona_ports:
  - 3306/tcp
  - 4567/tcp
  - 4568/tcp
  - 4444/tcp

mysql_remove_packages:
  - mysql
  - mysql-devel
  - mysql-libs

percona_repos:
  - https://repo.percona.com/yum/percona-release-latest.noarch.rpm
  - epel-release

percona_packages:
  - Percona-XtraDB-Cluster-57
  - MySQL-python

selinux_dir: /etc/selinux/config
mysql_root_password: Quang12345@#$

mysql_config: /etc/percona-xtradb-cluster.conf.d/wsrep.cnf

cluster_name: percona_cluster

mysql_user_sst: 'sstuser'
mysql_password_sst: 's3cretVT'

mysql_user: 'voice_otp'
mysql_password: 'Voice_otp#2021'
mysql_database: voiceotp